Scale Integration & Design Update to comply with Brand-Design
opentelekomcloud/otcdocstheme pull request #15
Opened 2021-12-06 10:15 UTC by SebastianGode

2021-12-06 11:54 UTC, tischrei requested changes

2021-12-06 11:54 UTC, tischrei commented on otcdocstheme/theme/otcdocs/footer.html
> +  // footer_shell.footerNavigation = [
delete comments

2021-12-06 13:24 UTC, SebastianGode commented
Current look if we would merge this PR:
![image](https://user-images.githubusercontent.com/70581801/144853766-c0336341-52c5-476c-8f6b-2c75559f7cd6.png)

2021-12-06 13:47 UTC, gtema requested changes
uhhhh, adding 2.1 thousand files is a very very bad way. Can we update build process to get everything what's required without putting those under git?

2021-12-06 14:14 UTC, tischrei commented
> uhhhh, adding 2.1 thousand files is a very very bad way. Can we update build process to get everything what's required without putting those under git?

Let's use the CDN for scale which is there since last week...

2021-12-06 14:15 UTC, SebastianGode commented
@gtema Removed all the node module stuff and added CDN

2021-12-07 13:01 UTC, tischrei submitted a review, later dismissed

2021-12-07 14:38 UTC, tischrei submitted a review, later dismissed

2021-12-08 10:40 UTC, tischrei approved these changes

2021-12-13 09:55 UTC, gtema approved these changes

2021-12-13 10:04 UTC, merged