Add directives
opentelekomcloud/otcdocstheme pull request #150
Opened 2023-03-15 14:07 UTC by SebastianGode

2023-03-17 09:15 UTC, SebastianGode commented
recheck

2023-03-21 18:28 UTC, gtema requested changes

2023-03-21 18:28 UTC, gtema commented on doc/requirements.txt
> +git+https://github.com/opentelekomcloud/otc-sphinx-directives.git@error_fix#egg=otc_sphinx_directives
please never never never do that in a project like that

2023-03-21 18:28 UTC, gtema commented on doc/requirements.txt
> +git+https://gitea.eco.tsi-dev.otc-service.com/infra/otc-metadata.git#egg=otc_metadata
this repo should really NEVER get such dependency

2023-03-22 08:55 UTC, tischrei commented on doc/requirements.txt
> +git+https://github.com/opentelekomcloud/otc-sphinx-directives.git#egg=otc_sphinx_directives
That's not a "real PR" we wanna see how the behavior is.

2023-03-22 08:55 UTC, tischrei commented on doc/requirements.txt
> +git+https://github.com/opentelekomcloud/otc-sphinx-directives.git#egg=otc_sphinx_directives
I converted it to draft to make it clear.

2023-04-05 13:09 UTC, tischrei commented
not needed anymore

2023-04-05 13:09 UTC, closed without merging