Switch to bootstrap5
opentelekomcloud/otcdocstheme pull request #32
Opened 2022-02-01 08:36 UTC by gtema

- add bootstrap5 content
- switch to grid layout (sidebar left, toctree right, etc)

2022-02-01 14:26 UTC, gtema commented
this PR additionally does a full cleanup of old and unused content

2022-02-01 15:53 UTC, tischrei commented
Mmmh, looks a bit shitty; especially the api-ref stuff and I did not start to talk about the functionality of several buttons etc. We should discuss this is a meeting with more people than us.
But the current result does not change my opinion that I am satisfied with the switch to BS5 or we have to spent additional weeks of tuning and drop the work done in the past couple of weeks.

2022-02-01 15:55 UTC, gtema commented
oh yeah, api-ref I missed completely

2022-02-01 15:57 UTC, tischrei commented
I am not completely against turning to BS5, but it is sad that we waste lot of time in tuning the old crap. That's a bit sad.

2022-02-01 16:16 UTC, gtema commented
that is not an argument to stick to ancient toolset and continue fighting with those overrides. Atm there is no need to have "!important" overrides at all (maybe just one). From my pov it is worth of doing switch - this will make like easier in future. Will work on fixing api-ref later today

2022-02-01 17:57 UTC, gtema commented
actually all of the changes for api-ref need to be done in otc-api-ref now. I will take care setting up jobs that test this 2 projects together

2022-02-02 08:23 UTC, SebastianGode requested changes

2022-02-02 08:23 UTC, SebastianGode commented on otcdocstheme/theme/otcdocs/static/css/bootstrap.css
> + * Bootstrap v5.1.3 (https://getbootstrap.com/)
We do not need the non-minified version

2022-02-02 08:38 UTC, gtema commented
I know, I am still working on it (explicitly this is being deleted), but not pushed due to work on api-ref part

2022-02-02 16:40 UTC, outcatcher commented on doc/requirements.txt
> +# otc-api-ref needs otcdocstheme which needs os-api-ref (cycle dep).
There seems to be no cycle dependency in the second case.

2022-02-03 12:10 UTC, tischrei approved these changes

2022-02-03 12:11 UTC, tischrei approved these changes

2022-02-03 12:22 UTC, SebastianGode approved these changes

2022-02-03 12:38 UTC, merged