Left Sidebar changes
opentelekomcloud/otcdocstheme pull request #65
Opened 2022-03-14 08:51 UTC by SebastianGode

closes #61 
closes #58 
closes #59

2022-03-14 09:19 UTC, SebastianGode commented
This will make the left sidebar background grey, add a border and highlight deeply linked pages.

2022-03-17 08:09 UTC, SebastianGode commented
@gtema 
I now removed the greyish look (I also didn't like it, but meeting set we want that) and just added a border.

2022-03-17 09:07 UTC, gtema requested changes
yeah, border is now fine. But 0.8rem font size is pretty small. I wouldn't reduce it. Let's search for alternative to put more content into the menu

2022-03-17 12:36 UTC, gtema approved these changes

2022-03-17 12:37 UTC, tischrei approved these changes

2022-03-17 12:48 UTC, merged