Various fixes
opentelekomcloud/otcdocstheme pull request #90
Opened 2022-03-31 08:50 UTC by gtema

- add disable/display options
- reorg layout to better match sphinx layout

2022-03-31 09:57 UTC, tischrei requested changes
I would propose to enable search also in preview documentation. Otherwise the search is hidden etc.

2022-03-31 10:00 UTC, SebastianGode submitted a review, later dismissed

2022-03-31 10:34 UTC, gtema commented
> I would propose to enable search also in preview documentation. Otherwise the search is hidden etc.

good catch. Corrected the condition

2022-04-01 07:47 UTC, SebastianGode approved these changes

2022-04-01 08:41 UTC, tischrei approved these changes

2022-04-01 08:57 UTC, merged